defaultProject: project-f5aa7f27-0184-4aa1-9b9
defaultDataset: "Baseball-DW"
defaultAssertionDataset: dataform_assertions
dataformCoreVersion: 3.0.42
vars:
    # define datasets
    staging : "baseball_STG"
    DW : "baseball_DW"
    backup_DW : "baseball_DW_bkp"
    source_project_id : "bigquery-public-data"
    source_dataset_id : "baseball"
    
    


